[package]
name = "zenit"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
colored = "2.1"
indicatif = "0.17"
tokio = { version = "1.40", features = ["full"] }
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
dirs = "5.0"
